#!/usr/bin/env bash
# Set up ESPHome dev environment

set -e

cd "$(dirname "$0")/.."
venv_path=venv
location="${venv_path}"/bin/activate
if [ ! -n "$VIRTUAL_ENV" ] && [ ! "$ESPHOME_NO_VENV" ]; then
  python3 -m venv venv
  if [ -f venv/Scripts/activate ]; then
    location="venv/Scripts/activate"
  fi
fi

pip="${venv_path}"/bin/pip3
pre_commit="${venv_path}"/bin/pre-commit
python="${venv_path}"/bin/python3
if [ ! -n "$VIRTUAL_ENV" ] && [ ! "$ESPHOME_NO_VENV" ]; then
  pip=pip3
  pre_commit=pre-commit
  python=python3
fi

"${pip}" install -r requirements.txt -r requirements_optional.txt -r requirements_test.txt -r requirements_dev.txt
"${pip}" install setuptools wheel
"${pip}" install -e ".[dev,test,displays]" --config-settings editable_mode=compat

"${pre_commit}" install

"${python}" script/platformio_install_deps.py platformio.ini --libraries --tools --platforms

echo
echo
echo "Virtual environment created. Run 'source $location' to use it."
